// <auto-generated />
using EnumKeysSample;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnumKeysSample.Migrations
{
    [DbContext(typeof(WineContext))]
    [Migration("20230924133134_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("EnumKeysSample.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("Wines");
                });

            modelBuilder.Entity("EnumKeysSample.WineTypeDetails", b =>
                {
                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Type");

                    b.ToTable("WineTypes");

                    b.HasData(
                        new
                        {
                            Type = 1,
                            Name = "Red"
                        },
                        new
                        {
                            Type = 2,
                            Name = "White"
                        });
                });

            modelBuilder.Entity("EnumKeysSample.Wine", b =>
                {
                    b.HasOne("EnumKeysSample.WineTypeDetails", "TypeDetails")
                        .WithMany("Wines")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeDetails");
                });

            modelBuilder.Entity("EnumKeysSample.WineTypeDetails", b =>
                {
                    b.Navigation("Wines");
                });
#pragma warning restore 612, 618
        }
    }
}
